-- require("configs/change-kitty-bg")
require("configs/treesitter")
require("configs/fff")
require("configs/gitsigns")
require("configs/comment")
require("configs/nvimtree")
require("configs/lspkind")
require("configs/colorizer")
require("configs/luasnip")
require("configs/lualine")
require("configs/context")
